### ISSUE TITLE
Handle non-resolving hostnames in RetryingChannel

### ISSUE THREAD

**Issue by henryptung** [palantir/dialogue#1575]
## What happened?

In a Rubix environment, nodes that are bouncing will have their hostnames no longer resolve rather than causing socket timeouts. Example stacktrace:

```
com.palantir.dialogue.DialogueException: Network transport failure
	at com.palantir.conjure.java.dialogue.serde.DefaultClients.block(DefaultClients.java:142)
	at com.palantir.conjure.java.dialogue.serde.DefaultClients.callBlocking(DefaultClients.java:76)
	at com.palantir.conjure.java.client.jaxrs.DialogueFeignClient.execute(DialogueFeignClient.java:104)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:98)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:77)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:102)
        <snip/>
Caused by: java.net.UnknownHostException: <snip/>.svc.cluster.local
	at java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1509)
	at java.net.InetAddress.getAllByName(InetAddress.java:1368)
	at java.net.InetAddress.getAllByName(InetAddress.java:1302)
	at org.apache.hc.client5.http.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:43)
	at com.palantir.dialogue.hc5.InstrumentedDnsResolver.resolve(InstrumentedDnsResolver.java:45)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
	at com.palantir.dialogue.hc5.InstrumentedPoolingHttpClientConnectionManager.connect(InstrumentedPoolingHttpClientConnectionManager.java:81)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
	at com.palantir.dialogue.hc5.ApacheHttpClientBlockingChannel.execute(ApacheHttpClientBlockingChannel.java:107)
	at com.palantir.dialogue.blocking.BlockingChannelAdapter$BlockingChannelAdapterChannel$BlockingChannelAdapterTask.run(BlockingChannelAdapter.java:139)
	at com.palantir.dialogue.blocking.DefaultCallingThreadExecutor.executeQueue(DefaultCallingThreadExecutor.java:57)
	at com.palantir.conjure.java.dialogue.serde.DefaultClients.callBlocking(DefaultClients.java:75)
	... 78 more
	Suppressed: com.palantir.dialogue.hc5.ApacheHttpClientBlockingChannel$Diagnostic: Client Failure Diagnostic Information
```

## What did you want to happen?

Dialogue client should treat the respective node/host as down and fail over to another.

**Comment by henryptung** [comment]
Hmm, this should actually be caught as an IOException. Needs more digging...
