### ISSUE TITLE
RetryingChannel stacktraces do not contain useful signal for dialogue _users_

### ISSUE THREAD

**Issue by iamdanfox** [palantir/dialogue#736]
## What happened?

In production and in tests, there are tons and tons of this identical stacktrace:

```
com.palantir.logsafe.exceptions.SafeRuntimeException: Received retryable response: {status=429}
	at com.palantir.dialogue.core.RetryingChannel.lambda$static$1(RetryingChannel.java:84)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.incrementFailuresAndMaybeRetry(RetryingChannel.java:282)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.handleHttpResponse(RetryingChannel.java:255)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:267)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:258)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.blocking.BlockingChannelAdapter$BlockingChannelAdapterChannel$BlockingChannelAdapterTask.run(BlockingChannelAdapter.java:129)
	at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:501)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.palantir.tritium.metrics.TaggedMetricsThreadFactory$InstrumentedTask.run(TaggedMetricsThreadFactory.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-05-12 16:04:47,789 INFO [dialogue-blocking-channel-1] com.palantir.dialogue.core.RetryingChannel - Retrying call after failure
com.palantir.logsafe.exceptions.SafeRuntimeException: Received retryable response: {status=429}
	at com.palantir.dialogue.core.RetryingChannel.lambda$static$1(RetryingChannel.java:84)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.incrementFailuresAndMaybeRetry(RetryingChannel.java:282)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.handleHttpResponse(RetryingChannel.java:255)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:267)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:258)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.blocking.BlockingChannelAdapter$BlockingChannelAdapterChannel$BlockingChannelAdapterTask.run(BlockingChannelAdapter.java:129)
	at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:501)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.palantir.tritium.metrics.TaggedMetricsThreadFactory$InstrumentedTask.run(TaggedMetricsThreadFactory.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-05-12 16:04:47,789 INFO [dialogue-blocking-channel-35] com.palantir.dialogue.core.RetryingChannel - Retrying call after failure
com.palantir.logsafe.exceptions.SafeRuntimeException: Received retryable response: {status=429}
	at com.palantir.dialogue.core.RetryingChannel.lambda$static$1(RetryingChannel.java:84)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.incrementFailuresAndMaybeRetry(RetryingChannel.java:282)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.handleHttpResponse(RetryingChannel.java:255)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:267)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:258)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.blocking.BlockingChannelAdapter$BlockingChannelAdapterChannel$BlockingChannelAdapterTask.run(BlockingChannelAdapter.java:129)
	at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:501)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.palantir.tritium.metrics.TaggedMetricsThreadFactory$InstrumentedTask.run(TaggedMetricsThreadFactory.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-05-12 16:04:47,801 INFO [dialogue-blocking-channel-19] com.palantir.dialogue.core.RetryingChannel - Retrying call after failure
com.palantir.logsafe.exceptions.SafeRuntimeException: Received retryable response: {status=429}
	at com.palantir.dialogue.core.RetryingChannel.lambda$static$1(RetryingChannel.java:84)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.incrementFailuresAndMaybeRetry(RetryingChannel.java:282)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.handleHttpResponse(RetryingChannel.java:255)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:267)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:258)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.blocking.BlockingChannelAdapter$BlockingChannelAdapterChannel$BlockingChannelAdapterTask.run(BlockingChannelAdapter.java:129)
	at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:501)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.palantir.tritium.metrics.TaggedMetricsThreadFactory$InstrumentedTask.run(TaggedMetricsThreadFactory.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

These stacktraces record information that could theoretically be useful to dialogue _maintainers_, but are not useful to users.

## What did you want to happen?

I'd propose turning these off, perhaps unless people have explicitly enabled debug/trace logging for RetryingChannel?

**Comment by carterkozak** [comment]
If we log the response status I think it’s reasonable to exclude the stack trace, but in cases the client produces an exception I’d prefer to log it at info.

**Comment by iamdanfox** [comment]
Ok have implemented that here https://github.com/palantir/dialogue/pull/737
