### ISSUE TITLE
ReloadingClientFactory throws BootstrapMethodError

### ISSUE THREAD

**Issue by jonsyu1** [palantir/dialogue#760]
## What happened?
Calling `ReloadingClientFactory::get` throws a `BootstrapMethodError` when `hostEventsSink` is unspecified.

## What did you want to happen?
Leaving `hostEventsSink` unspecified should not cause `ReloadingClientFactory::get` to throw.

**Comment by carterkozak** [comment]
Can you provide more information, perhaps including a stack trace and the versions of CJR and Dialogue libraries?

**Comment by jonsyu1** [comment]
```
com.palantir.dialogue:dialogue-clients:1.43.0 (1 constraints: 3a053e3b)
com.palantir.conjure.java:conjure-java-undertow-runtime:5.15.0 (3 constraints: 93339c3f)
com.palantir.conjure.java.runtime:conjure-java-jersey-server:5.7.2 (2 constraints: 7b20702f)
```

```
Caused by: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: com.palantir.conjure.java.client.config.ImmutableClientConfiguration$Builder.hostEventsSink(Lcom/palantir/conjure/java/client/config/HostEventsSink;)Lcom/palantir/conjure/java/client/config/ClientConfiguration$Builder;
	at com.palantir.dialogue.clients.AugmentClientConfig.getClientConf(AugmentClientConfig.java:85)
	at com.palantir.dialogue.clients.ChannelCache.getApacheClient(ChannelCache.java:148)
	at com.palantir.dialogue.clients.ChannelCache.createNonLiveReloadingChannel(ChannelCache.java:115)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2341)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2339)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2322)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
	at com.palantir.dialogue.clients.ChannelCache.getNonReloadingChannel(ChannelCache.java:99)
	at com.palantir.dialogue.clients.ReloadingClientFactory.lambda$getChannel$3(ReloadingClientFactory.java:113)
	at com.palantir.refreshable.DefaultRefreshable.map(DefaultRefreshable.java:138)
	at com.palantir.dialogue.clients.ReloadingClientFactory.getChannel(ReloadingClientFactory.java:89)
	at com.palantir.dialogue.clients.ReloadingClientFactory.get(ReloadingClientFactory.java:72)

**Comment by iamdanfox** [comment]
So I'd be particularly interested in `com.palantir.conjure.java.runtime:client-config`, because that's where the new HostEventsSink class lives: https://github.com/palantir/conjure-java-runtime/blob/develop/client-config/src/main/java/com/palantir/conjure/java/client/config/HostEventsSink.java

**Comment by jonsyu1** [comment]
```
com.palantir.conjure.java.runtime:client-config:5.9.1 (8 constraints: 3a9b1588)

**Comment by iamdanfox** [comment]
Ok so 5.9.1 _should_ be fine, because my PR was released in 5.9.0 https://github.com/palantir/conjure-java-runtime/pull/1591. I have tests that show ReloadingClientFactory working fine without throwing this error, so I think there might be something strange about your dependencies.

The `BootstrapMethodError` says:

> Thrown to indicate that an invokedynamic instruction has failed to find its bootstrap method, or the bootstrap method has failed to provide a call site with a target of the correct method type.

And the line it's referencing is AugmentClientConfig.java:L85 (where builder is a `ClientConfiguration.builder`)

```java
        augment.hostEventsSink().ifPresent(builder::hostEventsSink);
```

Are you absolutely _sure_ that client-config.5.9.1 is on the prod classpath? Are there _any_ unusual classloaders going on in your project? Can you repro it from unit tests / gradle / intellij / any other project?

**Comment by jonsyu1** [comment]
> Are you absolutely sure that client-config.5.9.1 is on the prod classpath?

I pulled the version from my version lockfile.

> Are there any unusual classloaders going on in your project?

Yup, this is being run in flink via yarn.

> Can you repro it from unit tests / gradle / intellij / any other project?

I was unable to repro this in unit tests. In my unit tests, the user agent is required:
```
com.palantir.logsafe.exceptions.SafeIllegalArgumentException: userAgent must be specified

	at com.palantir.logsafe.Preconditions.checkArgument(Preconditions.java:53)
	at com.palantir.dialogue.core.Config.check(Config.java:68)
	at com.palantir.dialogue.core.ImmutableConfig.validate(ImmutableConfig.java:484)
	at com.palantir.dialogue.core.ImmutableConfig.access$1600(ImmutableConfig.java:32)
	at com.palantir.dialogue.core.ImmutableConfig$Builder.build(ImmutableConfig.java:665)
	at com.palantir.dialogue.core.DialogueChannel$Builder.buildNonLiveReloading(DialogueChannel.java:233)
	at com.palantir.dialogue.clients.ChannelCache.createNonLiveReloadingChannel(ChannelCache.java:124)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2341)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2339)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2322)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
	at com.palantir.dialogue.clients.ChannelCache.getNonReloadingChannel(ChannelCache.java:99)
	at com.palantir.dialogue.clients.ReloadingClientFactory.lambda$getChannel$3(ReloadingClientFactory.java:113)
	at com.palantir.refreshable.DefaultRefreshable.map(DefaultRefreshable.java:138)
	at com.palantir.dialogue.clients.ReloadingClientFactory.getChannel(ReloadingClientFactory.java:89)
	at com.palantir.dialogue.clients.ReloadingClientFactory.get(ReloadingClientFactory.java:72)

**Comment by jonsyu1** [comment]
I filled in the throwable message in my stacktrace above. Here's the message by itself:
```
java.lang.NoSuchMethodError: com.palantir.conjure.java.client.config.ImmutableClientConfiguration$Builder.hostEventsSink(Lcom/palantir/conjure/java/client/config/HostEventsSink;)Lcom/palantir/conjure/java/client/config/ClientConfiguration$Builder;
```

This does seem like a classloader issue.

**Comment by jonsyu1** [comment]
I confirmed the classloader issue by vendoring the dialogue-clients and client-config source.

It looks like the client-config dependency was outdated in the service that submits the tasks to yarn:

```
service/lib/client-config-5.7.0.jar
```

Upgrading the client-config dependency in the orchestration service did the trick! Thanks for your help debugging this 😄

**Comment by iamdanfox** [comment]
Ooof. Glad you got to the bottom of this - is it possible to fix in the orchestration service's classloader to prefer submitted jars rather than it's own?

**Comment by carterkozak** [comment]
child-first classloaders run into problems with shared infrastructure. If we consider slf4j bindings, logging may get thrown out :-/
